/*
 * Copyright (C) 2008 Security Engineering Research Group, 
 * Institute of Management Sciences, Peshawar, Pakistan.
 * http://serg.imsciences.edu.pk 
 * authors: Nauman and Tamleek 
 */

package edu.serg.mba.wsa.attserv;

public enum ResultType {
	VERIFICATION_SUCCESSFUL, VERIFICATION_FAILED_NONCE, VERIFICATION_FAILED_PCR_MISMATCH, VERIFICATION_FAILED_UNKNOWN, VERIFICATION_FAILED_NO_PCRS, NONCE_MISMATCH, NONCE_MATCH_SUCCESSFUL, SML_VERIFICATION_SUCCESSFUL, SML_VERIFICATION_PCR_MISMATCH, SML_VERIFICATION_VULNERABILITY, SML_VERIFICATION_HASH_UNKNOWN, SML_VERIFICATION_FAILED_UNKNOWN
}
